/*
 * rcc_driver.h
 *
 *  Created on: Nov 23, 2025
 *      Author: chris
 */

#ifndef DRIVERS_RCC_DRIVER_H_
#define DRIVERS_RCC_DRIVER_H_

#include "memorymap.h"
#include "typedefs.h"
#include "peripherals.h"

/* Clock control register CR */
#define RCC_CR_HSION_Pos            0U
#define RCC_CR_HSION_Msk            (1U << RCC_CR_HSION_Pos)
#define RCC_CR_HSION_EN             RCC_CR_HSION_Msk

#define RCC_CR_HSIRDY_Pos            1U
#define RCC_CR_HSIRDY_Msk            (1U << RCC_CR_HSIRDY_Pos)
#define RCC_CR_HSIRDY_EN             RCC_CR_HSIRDY_Msk

#define RCC_CR_HSEON_Pos            16U
#define RCC_CR_HSEON_Msk            (1U << RCC_CR_HSEON_Pos)
#define RCC_CR_HSEON_EN             RCC_CR_HSEON_Msk

#define RCC_CR_HSERDY_Pos           17U
#define RCC_CR_HSERDY_Msk           (1U << RCC_CR_HSERDY_Pos)
#define RCC_CR_HSERDY_EN            RCC_CR_HSERDY_Msk

#define RCC_CR_PLLON_Pos            24U
#define RCC_CR_PLLON_Msk            (1U << RCC_CR_PLLON_Pos)
#define RCC_CR_PLLON_EN             RCC_CR_PLLON_Msk

#define RCC_CR_PLLRDY_Pos           25U
#define RCC_CR_PLLRDY_Msk           (1U << RCC_CR_PLLRDY_Pos)
#define RCC_CR_PLLRDY_EN            RCC_CR_PLLRDY_Msk

/* Clock configuration register CFGR */
#define RCC_CFGR_SW_Pos             0U
#define RCC_CFGR_SW_Msk             (0x2U << RCC_CFGR_SW_Pos)
#define RCC_CFGR_SW_EN(x)           (x << RCC_CFGR_SW_Pos)

#define RCC_CFGR_SWS_Pos            2U
#define RCC_CFGR_SWS_Msk            (0x2U << RCC_CFGR_SWS
#define RCC_CFGR_SWS_EN(x)          (x << RCC_CFGR_SWS_Pos)

#define RCC_CFGR_HPRE_Pos           4U
#define RCC_CFGR_HPRE_Msk           (0xFU << RCC_CFGR_HPRE_Pos)
#define RCC_CFGR_HPRE_EN(x)         (x << RCC_CFGR_HPRE_Pos)

#define RCC_CFGR_PPRE1_Pos          8U
#define RCC_CFGR_PPRE1_Msk          (0x7U << RCC_CFGR_PPRE1_Pos)
#define RCC_CFGR_PPRE1_EN(x)        (x << RCC_CFGR_PPRE1_Pos)

#define RCC_CFGR_PPRE2_Pos          11U
#define RCC_CFGR_PPRE2_Msk          (0x7U << RCC_CFGR_PPRE2_Pos)
#define RCC_CFGR_PPRE2_EN(x)        (x << RCC_CFGR_PPRE2_Pos)

#define RCC_CFGR_PLLSRC_Pos        15U
#define RCC_CFGR_PLLSRC_Msk        (0x3U << RCC_CFGR_PLLSRC_Pos)
#define RCC_CFGR_PLLSRC_EN(x)      (x << RCC_CFGR_PLLSRC_Pos)

#define RCC_CFGR_PLLXTPRE_Pos      17U
#define RCC_CFGR_PLLXTPRE_Msk      (0x1U << RCC_CFGR_PLLXTPRE_Pos)
#define RCC_CFGR_PLLXTPRE_EN(x)    (x << RCC_CFGR_PLLXTPRE_Pos) 

#define RCC_CFGR_PLLMUL_Pos       18U
#define RCC_CFGR_PLLMUL_Msk       (0xFU << RCC_CFGR_PLLMUL_Pos)
#define RCC_CFGR_PLLMUL_EN(x)     (x << RCC_CFGR_PLLMUL_Pos)

#define RCC_CFGR_USBPRE_Pos      22U
#define RCC_CFGR_USBPRE_Msk      (0x1U << RCC_CFGR_USBPRE_Pos)
#define RCC_CFGR_USBPRE_EN(x)    (x << RCC_CFGR_USBPRE_Pos)

#define RCC_CFGR_MCO_Pos         24U
#define RCC_CFGR_MCO_Msk         (0x7U << RCC_CFGR_MCO_Pos)
#define RCC_CFGR_MCO_EN(x)       (x << RCC_CFGR_MCO_Pos)

#define RCC_CFGR_MCOPRE_Pos      28U
#define RCC_CFGR_MCOPRE_Msk      (0x7U << RCC_CFGR_MCOPRE_Pos)
#define RCC_CFGR_MCOPRE_EN(x)    (x << RCC_CFGR_MCOPRE_Pos) 

#define RCC_CFGR_PLLNODIV_Pos   31U
#define RCC_CFGR_PLLNODIV_Msk   (0x1U << RCC_CFGR_PLLNODIV_Pos)
#define RCC_CFGR_PLLNODIV_EN(x) (x << RCC_CFGR_PLLNODIV_Pos)

/* AHB peripheral clock enable register */
#define RCC_AHBENR_DMA1EN_Pos        0U
#define RCC_AHBENR_DMA1EN_Msk        (1U << RCC_AHBENR_DMA1EN_Pos)
#define RCC_AHBENR_DMA1EN_EN         RCC_AHBENR_DMA1EN_Msk
#define RCC_AHBENR_DMA2EN_Pos        1U
#define RCC_AHBENR_DMA2EN_Msk        (1U << RCC_AHBENR_DMA2EN_Pos)
#define RCC_AHBENR_DMA2EN_EN         RCC_AHBENR_DMA2EN_Msk
#define RCC_AHBENR_SRAMEN_Pos        2U
#define RCC_AHBENR_SRAMEN_Msk        (1U << RCC_AHBENR_SRAMEN_Pos)
#define RCC_AHBENR_SRAMEN_EN         RCC_AHBENR_SRAMEN_Msk
#define RCC_AHBENR_FLITFEN_Pos       4U
#define RCC_AHBENR_FLITFEN_Msk       (1U << RCC_AHBENR_FLITFEN_Pos)
#define RCC_AHBENR_FLITFEN_EN        RCC_AHBENR_FLITFEN_Msk
#define RCC_AHBENR_FMCEN_Pos          5U
#define RCC_AHBENR_FMCEN_Msk          (1U << RCC_AHBENR_FMCEN_Pos)
#define RCC_AHBENR_FMCEN_EN           RCC_AHBENR_FMCEN_Msk
#define RCC_AHBENR_CRCEN_Pos         6U
#define RCC_AHBENR_CRCEN_Msk         (1U << RCC_AHBENR_CRCEN_Pos)
#define RCC_AHBENR_CRCEN_EN          RCC_AHBENR_CRCEN_Msk
#define RCC_AHBENR_GPIOHEN_Pos       16U
#define RCC_AHBENR_GPIOHEN_Msk       (1U << RCC_AHBENR_GPIOHEN_Pos)
#define RCC_AHBENR_GPIOHEN_EN        RCC_AHBENR_GPIOHEN_Msk
#define RCC_AHBENR_GPIOAEN_Pos       17U
#define RCC_AHBENR_GPIOAEN_Msk       (1U << RCC_AHBENR_GPIOAEN_Pos)
#define RCC_AHBENR_GPIOAEN_EN        RCC_AHBENR_GPIOAEN_Msk
#define RCC_AHBENR_GPIOBEN_Pos       18U
#define RCC_AHBENR_GPIOBEN_Msk       (1U << RCC_AHBENR_GPIOBEN_Pos)
#define RCC_AHBENR_GPIOBEN_EN        RCC_AHBENR_GPIOBEN_Msk
#define RCC_AHBENR_GPIOCEN_Pos       19U
#define RCC_AHBENR_GPIOCEN_Msk       (1U << RCC_AHBENR_GPIOCEN_Pos)
#define RCC_AHBENR_GPIOCEN_EN        RCC_AHBENR_GPIOCEN_Msk
#define RCC_AHBENR_GPIODEN_Pos       20U
#define RCC_AHBENR_GPIODEN_Msk       (1U << RCC_AHBENR_GPIODEN_Pos)
#define RCC_AHBENR_GPIODEN_EN        RCC_AHBENR_GPIODEN_Msk
#define RCC_AHBENR_GPIOEEN_Pos       21U
#define RCC_AHBENR_GPIOEEN_Msk       (1U << RCC_AHBENR_GPIOEEN_Pos)
#define RCC_AHBENR_GPIOEEN_EN        RCC_AHBENR_GPIOEEN_Msk
#define RCC_AHBENR_GPIOFEN_Pos       22U
#define RCC_AHBENR_GPIOFEN_Msk       (1U << RCC_AHBENR_GPIOFEN_Pos)
#define RCC_AHBENR_GPIOFEN_EN        RCC_AHBENR_GPIOFEN_Msk
#define RCC_AHBENR_GPIOGEN_Pos       23U
#define RCC_AHBENR_GPIOGEN_Msk       (1U << RCC_AHBENR_GPIOGEN_Pos)
#define RCC_AHBENR_GPIOGEN_EN        RCC_AHBENR_GPIOGEN_Msk
#define RCC_AHBENR_ADC12EN_Pos      28U
#define RCC_AHBENR_ADC12EN_Msk      (1U << RCC_AHBENR_ADC12EN_Pos)
#define RCC_AHBENR_ADC12EN_EN       RCC_AHBENR_ADC12EN_Msk
#define RCC_AHBENR_ADC34EN_Pos      29U
#define RCC_AHBENR_ADC34EN_Msk      (1U << RCC_AHBENR_ADC34EN_Pos)
#define RCC_AHBENR_ADC34EN_EN       RCC_AHBENR_ADC34EN_Msk 

/* APB2 peripheral clock enable register */
#define RCC_APB2ENR_SYSCFGEN_Pos     0U
#define RCC_APB2ENR_SYSCFGEN_Msk     (1U << RCC_APB2ENR_SYSCFGEN_Pos)
#define RCC_APB2ENR_SYSCFGEN_EN      RCC_APB2ENR_SYSCFGEN_Msk
#define RCC_APB2ENR_TIM1EN_Pos      11U
#define RCC_APB2ENR_TIM1EN_Msk      (1U << RCC_APB2ENR_TIM1EN_Pos)
#define RCC_APB2ENR_TIM1EN_EN       RCC_APB2ENR_TIM1EN_Msk
#define RCC_APB2ENR_SPI1EN_Pos      12U
#define RCC_APB2ENR_SPI1EN_Msk      (1U << RCC_APB2ENR_SPI1EN_Pos)
#define RCC_APB2ENR_SPI1EN_EN       RCC_APB2ENR_SPI1EN_Msk
#define RCC_APB2ENR_TIM8EN_Pos      13U
#define RCC_APB2ENR_TIM8EN_Msk      (1U << RCC_APB2ENR_TIM8EN_Pos)
#define RCC_APB2ENR_TIM8EN_EN       RCC_APB2ENR_TIM8EN_Msk
#define RCC_APB2ENR_USART1EN_Pos    14U
#define RCC_APB2ENR_USART1EN_Msk    (1U << RCC_APB2ENR_USART1EN_Pos)
#define RCC_APB2ENR_USART1EN_EN     RCC_APB2ENR_USART1EN_Msk
#define RCC_APB2ENR_SPI4EN_Pos      15U
#define RCC_APB2ENR_SPI4EN_Msk      (1U << RCC_APB2ENR_SPI4EN_Pos)
#define RCC_APB2ENR_SPI4EN_EN       RCC_APB2ENR_SPI4EN_Msk
#define RCC_APB2ENR_TIM15EN_Pos     16U
#define RCC_APB2ENR_TIM15EN_Msk     (1U << RCC_APB2ENR_TIM15EN_Pos)
#define RCC_APB2ENR_TIM15EN_EN      RCC_APB2ENR_TIM15EN_Msk
#define RCC_APB2ENR_TIM16EN_Pos     17U
#define RCC_APB2ENR_TIM16EN_Msk     (1U << RCC_APB2ENR_TIM16EN_Pos)
#define RCC_APB2ENR_TIM16EN_EN      RCC_APB2ENR_TIM16EN_Msk
#define RCC_APB2ENR_TIM17EN_Pos     18U
#define RCC_APB2ENR_TIM17EN_Msk     (1U << RCC_APB2ENR_TIM17EN_Pos)
#define RCC_APB2ENR_TIM17EN_EN      RCC_APB2ENR_TIM17EN_Msk
#define RCC_APB2ENR_TIM20EN_Pos     20U
#define RCC_APB2ENR_TIM20EN_Msk     (1U << RCC_APB2ENR_TIM20EN_Pos)
#define RCC_APB2ENR_TIM20EN_EN      RCC_APB2ENR_TIM20EN_Msk

/* APB1 peripheral clock enable register */
#define RCC_APB1ENR_TIM2EN_Pos      0U
#define RCC_APB1ENR_TIM2EN_Msk      (1U << RCC_APB1ENR_TIM2EN_Pos)
#define RCC_APB1ENR_TIM2EN_EN       RCC_APB1ENR_TIM2EN_Msk
#define RCC_APB1ENR_TIM3EN_Pos      1U
#define RCC_APB1ENR_TIM3EN_Msk      (1U << RCC_APB1ENR_TIM3EN_Pos)
#define RCC_APB1ENR_TIM3EN_EN       RCC_APB1ENR_TIM3EN_Msk
#define RCC_APB1ENR_TIM4EN_Pos      2U
#define RCC_APB1ENR_TIM4EN_Msk      (1U << RCC_APB1ENR_TIM4EN_Pos)
#define RCC_APB1ENR_TIM4EN_EN       RCC_APB1ENR_TIM4EN_Msk
#define RCC_APB1ENR_TIM6EN_Pos      4U
#define RCC_APB1ENR_TIM6EN_Msk      (1U << RCC_APB1ENR_TIM6EN_Pos)
#define RCC_APB1ENR_TIM6EN_EN       RCC_APB1ENR_TIM6EN_Msk
#define RCC_APB1ENR_TIM7EN_Pos      5U
#define RCC_APB1ENR_TIM7EN_Msk      (1U << RCC_APB1ENR_TIM7EN_Pos)
#define RCC_APB1ENR_TIM7EN_EN       RCC_APB1ENR_TIM7EN_Msk
#define RCC_APB1ENR_WWDGEN_Pos      11U
#define RCC_APB1ENR_WWDGEN_Msk      (1U << RCC_APB1ENR_WWDGEN_Pos)
#define RCC_APB1ENR_WWDGEN_EN       RCC_APB1ENR_WWDGEN_Msk
#define RCC_APB1ENR_SPI2EN_Pos      14U
#define RCC_APB1ENR_SPI2EN_Msk      (1U << RCC_APB1ENR_SPI2EN_Pos)
#define RCC_APB1ENR_SPI2EN_EN       RCC_APB1ENR_SPI2EN_Msk
#define RCC_APB1ENR_SPI3EN_Pos      15U
#define RCC_APB1ENR_SPI3EN_Msk      (1U << RCC_APB1ENR_SPI3EN_Pos)
#define RCC_APB1ENR_SPI3EN_EN       RCC_APB1ENR_SPI3EN_Msk
#define RCC_APB1ENR_USART2EN_Pos    17U
#define RCC_APB1ENR_USART2EN_Msk    (1U << RCC_APB1ENR_USART2EN_Pos)
#define RCC_APB1ENR_USART2EN_EN     RCC_APB1ENR_USART2EN_Msk
#define RCC_APB1ENR_USART3EN_Pos    18U
#define RCC_APB1ENR_USART3EN_Msk    (1U << RCC_APB1ENR_USART3EN_Pos)
#define RCC_APB1ENR_USART3EN_EN     RCC_APB1ENR_USART3EN_Msk
#define RCC_APB1ENR_UART4EN_Pos     19U
#define RCC_APB1ENR_UART4EN_Msk     (1U << RCC_APB1ENR_UART4EN_Pos)
#define RCC_APB1ENR_UART4EN_EN      RCC_APB1ENR_UART4EN_Msk
#define RCC_APB1ENR_UART5EN_Pos     20U
#define RCC_APB1ENR_UART5EN_Msk     (1U << RCC_APB1ENR_UART5EN_Pos)
#define RCC_APB1ENR_UART5EN_EN      RCC_APB1ENR_UART5EN_Msk
#define RCC_APB1ENR_I2C1EN_Pos      21U
#define RCC_APB1ENR_I2C1EN_Msk      (1U << RCC_APB1ENR_I2C1EN_Pos)
#define RCC_APB1ENR_I2C1EN_EN       RCC_APB1ENR_I2C1EN_Msk
#define RCC_APB1ENR_I2C2EN_Pos      22U
#define RCC_APB1ENR_I2C2EN_Msk      (1U << RCC_APB1ENR_I2C2EN_Pos)
#define RCC_APB1ENR_I2C2EN_EN       RCC_APB1ENR_I2C2EN_Msk
#define RCC_APB1ENR_USBEN_Pos       23U
#define RCC_APB1ENR_USBEN_Msk       (1U << RCC_APB1ENR_USBEN_Pos)
#define RCC_APB1ENR_USBEN_EN        RCC_APB1ENR_USBEN_Msk
#define RCC_APB1ENR_CANEN_Pos       25U
#define RCC_APB1ENR_CANEN_Msk       (1U << RCC_APB1ENR_CANEN_Pos)
#define RCC_APB1ENR_CANEN_EN        RCC_APB1ENR_CANEN_Msk
#define RCC_APB1ENR_DAC2EN_Pos      26U
#define RCC_APB1ENR_DAC2EN_Msk      (1U << RCC_APB1ENR_DAC2EN_Pos)
#define RCC_APB1ENR_DAC2EN_EN       RCC_APB1ENR_DAC2EN_Msk
#define RCC_APB1ENR_PWREN_Pos       28U
#define RCC_APB1ENR_PWREN_Msk       (1U << RCC_APB1ENR_PWREN_Pos)
#define RCC_APB1ENR_PWREN_EN        RCC_APB1ENR_PWREN_Msk
#define RCC_APB1ENR_DAC1EN_Pos      29U
#define RCC_APB1ENR_DAC1EN_Msk      (1U << RCC_APB1ENR_DAC1EN_Pos)
#define RCC_APB1ENR_DAC1EN_EN       RCC_APB1ENR_DAC1EN_Msk
#define RCC_APB1ENR_I2C3EN_Pos      30U
#define RCC_APB1ENR_I2C3EN_Msk      (1U << RCC_APB1ENR_I2C3EN_Pos)
#define RCC_APB1ENR_I2C3EN_EN       RCC_APB1ENR_I2C3EN_Msk


// Activate AHB Peripheral Clocks
#define RCC_ENABLE_GPIOA()      (RCC->AHBENR |= RCC_AHBENR_GPIOAEN_EN)
#define RCC_ENABLE_GPIOB()      (RCC->AHBENR |= RCC_AHBENR_GPIOBEN_EN)
#define RCC_ENABLE_GPIOC()      (RCC->AHBENR |= RCC_AHBENR_GPIOCEN_EN)
#define RCC_ENABLE_GPIOD()      (RCC->AHBENR |= RCC_AHBENR_GPIODEN_EN)
#define RCC_ENABLE_GPIOE()      (RCC->AHBENR |= RCC_AHBENR_GPIOEEN_EN)
#define RCC_ENABLE_GPIOF()      (RCC->AHBENR |= RCC_AHBENR_GPIOFEN_EN)
#define RCC_ENABLE_GPIOG()      (RCC->AHBENR |= RCC_AHBENR_GPIOGEN_EN)
#define RCC_ENABLE_GPIOH()      (RCC->AHBENR |= RCC_AHBENR_GPIOHEN_EN)
#define RCC_ENABLE_DMA1()      (RCC->AHBENR |= RCC_AHBENR_DMA1EN_EN)
#define RCC_ENABLE_DMA2()      (RCC->AHBENR |= RCC_AHBENR_DMA2EN_EN)
#define RCC_ENABLE_CRC()        (RCC->AHBENR |= RCC_AHBENR_CRCEN_EN)
#define RCC_ENABLE_FLITF()      (RCC->AHBENR |= RCC_AHBENR_FLITFEN_EN)
#define RCC_ENABLE_SRAM()       (RCC->AHBENR |= RCC_AHBENR_SRAMEN_EN)
#define RCC_ENABLE_FMC()        (RCC->AHBENR |= RCC_AHBENR_FMCEN_EN)
#define RCC_ENABLE_ADC12()      (RCC->AHBENR |= RCC_AHBENR_ADC12EN_EN)
#define RCC_ENABLE_ADC34()      (RCC->AHBENR |= RCC_AHBENR_ADC34EN_EN)

/* Activate APB1 Peripheral clocks */
#define RCC_ENABLE_TIM2()       (RCC->APB1ENR |= RCC_APB1ENR_TIM2EN_EN)
#define RCC_ENABLE_TIM3()       (RCC->APB1ENR |= RCC_APB1ENR_TIM3EN_EN)
#define RCC_ENABLE_TIM4()       (RCC->APB1ENR |= RCC_APB1ENR_TIM4EN_EN)
#define RCC_ENABLE_TIM6()       (RCC->APB1ENR |= RCC_APB1ENR_TIM6EN_EN)
#define RCC_ENABLE_TIM7()       (RCC->APB1ENR |= RCC_APB1ENR_TIM7EN_EN)
#define RCC_ENABLE_WWDG()       (RCC->APB1ENR |= RCC_APB1ENR_WWDGEN_EN)
#define RCC_ENABLE_SPI2()       (RCC->APB1ENR |= RCC_APB1ENR_SPI2EN_EN)
#define RCC_ENABLE_SPI3()       (RCC->APB1ENR |= RCC_APB1ENR_SPI3EN_EN)
#define RCC_ENABLE_USART2()     (RCC->APB1ENR |= RCC_APB1ENR_USART2EN_EN)
#define RCC_ENABLE_USART3()     (RCC->APB1ENR |= RCC_APB1ENR_USART3EN_EN)
#define RCC_ENABLE_UART4()      (RCC->APB1ENR |= RCC_APB1ENR_UART4EN_EN)
#define RCC_ENABLE_UART5()      (RCC->APB1ENR |= RCC_APB1ENR_UART5EN_EN)
#define RCC_ENABLE_I2C1()       (RCC->APB1ENR |= RCC_APB1ENR_I2C1EN_EN)
#define RCC_ENABLE_I2C2()       (RCC->APB1ENR |= RCC_APB1ENR_I2C2EN_EN)
#define RCC_ENABLE_I2C3()       (RCC->APB1ENR |= RCC_APB1ENR_I2C3EN_EN)
#define RCC_ENABLE_USB()        (RCC->APB1ENR |= RCC_APB1ENR_USBEN_EN)
#define RCC_ENABLE_CAN()        (RCC->APB1ENR |= RCC_APB1ENR_CANEN_EN)
#define RCC_ENABLE_DAC1()       (RCC->APB1ENR |= RCC_APB1ENR_DAC1EN_EN)
#define RCC_ENABLE_DAC2()       (RCC->APB1ENR |= RCC_APB1ENR_DAC2EN_EN)
#define RCC_ENABLE_PWR()        (RCC->APB1ENR |= RCC_APB1ENR_PWREN_EN)

/* Activate APB2 Peripheral clocks */
#define RCC_ENABLE_SYSCFG()     (RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN_EN)
#define RCC_ENABLE_TIM1()       (RCC->APB2ENR |= RCC_APB2ENR_TIM1EN_EN)
#define RCC_ENABLE_SPI1()       (RCC->APB2ENR |= RCC_APB2ENR_SPI1EN_EN)
#define RCC_ENABLE_TIM8()       (RCC->APB2ENR |= RCC_APB2ENR_TIM8EN_EN)
#define RCC_ENABLE_USART1()     (RCC->APB2ENR |= RCC_APB2ENR_USART1EN_EN)
#define RCC_ENABLE_SPI4()       (RCC->APB2ENR |= RCC_APB2ENR_SPI4EN_EN)
#define RCC_ENABLE_TIM15()      (RCC->APB2ENR |= RCC_APB2ENR_TIM15EN_EN)
#define RCC_ENABLE_TIM16()      (RCC->APB2ENR |= RCC_APB2ENR_TIM16EN_EN)
#define RCC_ENABLE_TIM17()      (RCC->APB2ENR |= RCC_APB2ENR_TIM17EN_EN)
#define RCC_ENABLE_TIM20()      (RCC->APB2ENR |= RCC_APB2ENR_TIM20EN_EN)




void Driver_RCC_ClockSetup();


#endif /* DRIVERS_RCC_DRIVER_H_ */
